export const IS_CONFIRMED_SELECTED = "IS_CONFIRMED_SELECTED";
export const IS_ACTIVE_SELECTED = "IS_ACTIVE_SELECTED";
export const IS_RECOVERED_SELECTED = "IS_RECOVERED_SELECTED";
export const IS_DEATH_SELECTED = "IS_DEATH_SELECTED";
